// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function Close():Promise<void>;

export function FetchArticleContent(arg1:number,arg2:string):Promise<string>;

export function FetchCached():Promise<app.FetchResult>;

export function FetchEntries():Promise<app.FetchResult>;

export function GetConfig():Promise<config.Config>;

export function MarkRead(arg1:Array<number>):Promise<void>;

export function MarkUnread(arg1:Array<number>):Promise<void>;

export function Open(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function RefreshAndFetch():Promise<app.FetchResult>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveEntry(arg1:number):Promise<void>;

export function Show():Promise<void>;

export function ToggleStar(arg1:number):Promise<void>;
