// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function FetchArticleContent(arg1, arg2) {
  return window['go']['main']['App']['FetchArticleContent'](arg1, arg2);
}

export function FetchEntries() {
  return window['go']['main']['App']['FetchEntries']();
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function MarkUnread(arg1) {
  return window['go']['main']['App']['MarkUnread'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RefreshAndFetch() {
  return window['go']['main']['App']['RefreshAndFetch']();
}

export function SaveEntry(arg1) {
  return window['go']['main']['App']['SaveEntry'](arg1);
}

export function ToggleStar(arg1) {
  return window['go']['main']['App']['ToggleStar'](arg1);
}
